INSERT INTO ComicBooks (ItemID, Title, PublishingDate) VALUES ('CB001', 'Captain America ; Winter Soldier Special', TO_DATE('2022/11/16', 'yyyy/mm/dd'));
INSERT INTO ComicBooks (ItemID, Title, PublishingDate) VALUES ('CB002', 'Shang-Chi and the Ten Rings (2022)', TO_DATE('2022/11/16', 'yyyy/mm/dd'));
INSERT INTO ComicBooks (ItemID, Title, PublishingDate) VALUES ('CB003', 'The Amazing Spider-Man (2018) #1', TO_DATE('2018/07/11', 'yyyy/mm/dd'));
INSERT INTO ComicBooks (ItemID, Title, PublishingDate) VALUES ('CB004', 'Immortal Hulk (2018)', TO_DATE('2018/07/11', 'yyyy/mm/dd'));
INSERT INTO ComicBooks (ItemID, Title, PublishingDate) VALUES ('CB005', 'Thanos (2016)', TO_DATE('2016/11/16', 'yyyy/mm/dd'));
INSERT INTO ComicBooks (ItemID, Title, PublishingDate) VALUES ('CB006', 'THE DARK KNIGHT RETURNS (1986)', TO_DATE('1986/11/01', 'yyyy/mm/dd'));
INSERT INTO ComicBooks (ItemID, Title, PublishingDate) VALUES ('CB007', 'Jla: Earth 2', TO_DATE('2000/01/01', 'yyyy/mm/dd'));
INSERT INTO ComicBooks (ItemID, Title, PublishingDate) VALUES ('CB008', 'The Avengers', TO_DATE('1963/09/01', 'yyyy/mm/dd'));
INSERT INTO ComicBooks (ItemID, Title, PublishingDate) VALUES ('CB009', 'THE MAN OF STEEL', TO_DATE('1986/10/21', 'yyyy/mm/dd'));
INSERT INTO ComicBooks (ItemID, Title, PublishingDate) VALUES ('CB010', 'THE KILLING JOKE', TO_DATE('1988/03/01', 'yyyy/mm/dd'));