/*Clearing any previously existing formatting*/
CLEAR COLUMNS
CLEAR BREAKS
CLEAR COMPUTES
CLEAR SCREEN

/*Accept the OrderID from the user of choice*/
ACCEPT CUSTID NUMBER PROMPT 'Enter the Customer ID to be displayed: '

SET TERMOUT OFF

/*Updating the value of user variable report_date with SYSDATE returned from the database using the NEW_VALUE option of the COLUMN */
COLUMN TODAY NEW_VALUE report_date
SELECT TO_CHAR(SYSDATE, 'fmMonth DD,YYYY') TODAY FROM DUAL;

/*Providing custom header names for the columns*/
COLUMN ORDERID HEADING 'ORDER|ID'
COLUMN CUSTID HEADING 'CUSTOMER|ID'
COLUMN CUSTTYPE HEADING 'TYPE'
COLUMN NAME HEADING 'CUSTOMER|NAME'
COLUMN LINEID HEADING 'SLNO'
COLUMN ITEMID HEADING 'ITEM|ID'
COLUMN TAX HEADING 'TAX%'
COLUMN DISCOUNT HEADING 'DISCOUNT%'
COLUMN (O.QUANTITY*S.PRICE) HEADING 'SUBTOTAL' 
COLUMN DATEOFORDER HEADING 'ORDER|DATE'
COLUMN SHIPPEDDATE HEADING 'SHIPPED|DATE'
COLUMN SHIPPINGFEE HEADING 'SHIPPING|FEE'
COLUMN FINALCOST HEADING 'TOTAL'

/*Providing the formatting for the ouput of each column*/
COLUMN CUSTTYPE FORMAT A7 WORD_WRAPPED
COLUMN NAME FORMAT A10 WORD_WRAPPED
COLUMN ADDRESS FORMAT A15 WORD_WRAPPED
COLUMN TITLE FORMAT A15 WORD_WRAPPED
COLUMN ITEMID FORMAT A6 WORD_WRAPPED
COLUMN DATEOFORDER FORMAT A10
COLUMN SHIPPEDDATE FORMAT A10
COLUMN SHIPPINGFEE FORMAT 99999999
COLUMN TAX FORMAT 99
COLUMN LINEID FORMAT 99
COLUMN ORDERID FORMAT 9999
COLUMN CUSTID FORMAT 999
COLUMN PRICE FORMAT 999.99
COLUMN SUBTOTAL FORMAT 9999.99
COLUMN FINALCOST FORMAT 9999.99
COLUMN QUANTITY FORMAT 99999999

/*Providing the formatting for the whole page*/
SET PAGESIZE 24
SET LINESIZE 400
SET UNDERLINE =
SET RECSEP EACH
SET RECSEPCHAR "-"
SET NUMWIDTH 10

/*Creating the spool file to save the output to a text file*/
SPOOL CustomerOrdersOutput.txt 

BREAK ON ORDERID ON CUSTID ON CUSTTYPE ON NAME ON PHONE ON ADDRESS ON ORDERCOST ON TAX ON DISCOUNT ON SHIPPINGFEE ON FINALCOST SKIP 1 

/*Setting the title of the report to display at the top center of each page*/
TTITLE CENTER "CUSTOMER ORDER" SKIP 2-
CENTER report_date SKIP 2-
LEFT 'ORDER DETAILS' RIGHT 'PAGE:'-
FORMAT 999 SQL.PNO SKIP 2

/*Setting the title to display at the bottom center of each page*/
BTITLE CENTER "COPY FOR MANAGEMENT ONLY" SKIP 1-
CENTER "THANK YOU"

/*Running the query to get the necessary data*/
SELECT C.CUSTID, C.CUSTTYPE, C.NAME, C.PHONE, C.street, C.city, C.ZipCode, CO.ORDERID, O.LINEID, ITEM.ITEMID,
ITEM.TITLE, O.QUANTITY, S.PRICE, CO.DATEOFORDER, CO.SHIPPEDDATE, CO.ORDERCOST, CO.SHIPPINGFEE, CO.DISCOUNT, CO.TAX,  CO.FINALCOST
FROM (
    (SELECT * FROM CustOrder) CO
    LEFT OUTER JOIN 
    CUSTOMER C 
    ON CO.CUSTID = C.CUSTID
    LEFT OUTER JOIN 
    OrderLineItem O
    ON CO.ORDERID = O.ORDERID
    LEFT OUTER JOIN 
        (SELECT ITEMID, TITLE FROM COMICBOOKS
        UNION
        SELECT ITEMID, TITLE FROM CARTOONMOVIES) ITEM
    ON O.ITEMID=ITEM.ITEMID
    LEFT OUTER JOIN 
    STOREITEM S 
    ON ITEM.ITEMID = S.ITEMID)
WHERE C.CUSTID=&CUSTID
ORDER BY CO.ORDERID, LINEID;

SPOOL OFF

/*Clearing all the formatting*/
CLEAR COLUMNS
CLEAR BREAK 
TTITLE OFF
BTITLE OFF 
SET VERIFY OFF
SET FEEDBACK OFF
SET RECSEP OFF 
SET ECHO OFF
SET TERMOUT ON